<?php

/**
 * @file
 * Contains functions and hooks for the ithenticate module.
 */

use Drupal\ithenticate\entities\IthenticateDocument;
use Drupal\ithenticate\IthenticateApiRequest;
use Drupal\ithenticate\IthenticateRequestWrapper;
use Drupal\ithenticate\Methods\SubmitDocument;

/**
 * Implements hook_menu().
 */
function ithenticate_menu() {
  $items = [];

  $items['admin/config/services/ithenticate'] = [
    'title' => t('iThenticate'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ithenticate_admin_settings'],
    'access arguments' => ['administer ithenticate settings'],
    'file' => 'ithenticate.admin.inc',
  ];

  $items['node/%node/ithenticate'] = [
    'title' => t('iThenticate'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ithenticate_portal', 1],
    'access callback' => 'ithenticate_portal_access',
    'access arguments' => [1],
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function ithenticate_permission() {
  return [
    'administer ithenticate settings' => [
      'title' => 'Administer iThenticate settings',
    ],
    'access ithenticate portal' => [
      'title' => 'Access the ithenticate page for each allowed node',
    ]
  ];
}

/**
 * Access callback for the iThenticate portal page.
 *
 * @param object $node
 *   The node object.
 *
 * @return bool
 *   Whether the user has access.
 */
function ithenticate_portal_access($node) {
  return $node->type === 'paper' && user_access('access ithenticate portal');
}

/**
 * Callback for the iThenticate portal page.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function ithenticate_portal($form, &$form_state, $node) {
  _validate_ithenticate_is_configured();

  $form_state['#node'] = $node;
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid);
  if (empty($document) || empty($document->getIthenticateDocumentId())) {
    // Shows a form that allows the user to submit a document.
    $form['help'] = [
      '#type' => 'item',
      '#markup' => t('There are no records for the given document. Press below to submit for plagiarism check.'),
    ];

    $form['submit'] = [
      '#type' => 'submit',
      '#value' => t('Submit to iThenticate'),
      '#submit' => ['ithenticate_portal_submit_document'],
    ];
  }
  elseif (empty($document->getIthenticateReportUrl()) && !empty($document->getIthenticateDocumentId())) {
    $form['help'] = [
      '#type' => 'item',
      '#markup' => t('Click below to try and retrieve the report URL.'),
    ];

    $form['submit'] = [
      '#type' => 'submit',
      '#value' => t('Try to retrieve data'),
      '#submit' => ['ithenticate_portal_submit_fetch_results_submit'],
    ];
  }
  elseif (!empty($document->getIthenticateReportUrl())) {
    $form['help'] = [
      '#type' => 'item',
      // '#markup' => "<iframe src='{$document->getIthenticateReportUrl()}'></iframe>'",
      '#markup' => t("The report has been created. Please, go to <a href='!link' target='_blank'>iThenticate report page</a> for further details.", [
        '!link' => $document->getIthenticateReportUrl(),
      ]),
    ];
  }

  if (!empty($document)) {
    $form_state['document'] = $document;
  }

  return $form;
}

/**
 * Submits the document to the iThenticate service.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form_state array.
 */
function ithenticate_portal_submit_document($form, &$form_state) {
  $node = $form_state['#node'];

  $service = new IthenticateRequestWrapper();
  $document = $service->submitDocument($node);
  if ($document->getIthenticateDocumentId()) {
    // If we are here, the document has been submitted and a document ID is set.
    if ($service->checkIsDocumentReportPending($document->getIthenticateDocumentId())) {
      drupal_set_message(t('The report is being generated. Please, come back later.'));
    }
    else {
      $service->fetchDocumentReportId($document);
      $service->fetchDocumentReportUrl($document);
    }
  }
}

/**
 * Submits the document to the iThenticate service.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form_state array.
 */
function ithenticate_portal_submit_fetch_results_submit($form, &$form_state) {
  $node = $form_state['#node'];
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid);
  $service_wrapper = new IthenticateRequestWrapper();

  $service_wrapper->getReportData($document);
  $document->save();
}

/**
 * Checks whether config settings have been set.
 *
 * @return bool
 *   Whether the iThenticate settings are filled.
 */
function _validate_ithenticate_is_configured() {
  $username = variable_get('ithenticate_user_name', '');
  $password = variable_get('ithenticate_user_pass', '');
  $folder_number = variable_get('ithenticate_submission_folder_number', '');

  if (empty($username) || empty($password) || empty($folder_number)) {
    drupal_set_message(t('Please, first configure the iThenticate settings in the <a href="/admin/config/services/ithenticate">settings page</a>.'), 'error');
    return FALSE;
  }

  return TRUE;
}



/**
 * Implements hook_cron().
 */
function ithenticate_cron() {
  $queue = DrupalQueue::get('ithenticate_report_url');
  if ($queue->numberOfItems()) {
    return;
  }

  $document_ids = db_select('ithenticate_documents', 'i')
    ->fields('i', ['ithenticate_document_id'])
    ->isNotNull('ithenticate_document_id')
    ->isNull('ithenticate_report_url')
    ->execute()
    ->fetchCol();

  foreach ($document_ids as $document_id) {
    $queue->createItem($document_id);
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function ithenticate_cron_queue_info() {
  $queues = [];
  $queues['ithenticate_report_url'] = [
    'worker callback' => 'ithenticate_report_download_data',
    'time' => 30,
  ];

  return $queues;
}

/**
 * Attempts to retrieve the report URL for a document.
 *
 * @param int $document_id
 *   The document ID.
 */
function ithenticate_report_download_data($document_id) {
  $document = IthenticateDocument::loadByIthenticateDocumentId($document_id);
  if (!empty($document->getIthenticateReportUrl())) {
    // It has been updated in the meantime. Nothing to do here.
    return;
  }

  $service_wrapper = new IthenticateRequestWrapper();
  $service_wrapper->getReportData($document);
  $document->save();

  if (!empty($document->getIthenticateReportUrl())) {
    $send_email = variable_get('ithenticate_send_email_on_success', FALSE);
    $recipient = variable_get('ithenticate_email_recipient', NULL);
    if ($send_email && filter_var($recipient, FILTER_VALIDATE_EMAIL)) {
      $node = node_load($document->getEntityId());
      mail(
        $recipient,
        "iThenticate report for {$node->field_paper_id[LANGUAGE_NONE][0]['value']}",
        "A new iThenticate report has been generated. {$document->getIthenticateReportUrl()}"
      );
    }
  }
}
