<?php

/**
 * @file
 * Contains functions and hooks for the ithenticate module.
 */

use Drupal\ithenticate\entities\IthenticateDocument;
use Drupal\ithenticate\IthenticateApiRequest;
use Drupal\ithenticate\IthenticateRequestWrapper;
use Drupal\ithenticate\Methods\SubmitDocument;

/**
 * Implements hook_menu().
 */
function ithenticate_menu() {
  $items = [];

  $items['admin/config/services/ithenticate'] = [
    'title' => t('iThenticate'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ithenticate_admin_settings'],
    'access arguments' => ['administer ithenticate settings'],
    'file' => 'ithenticate.admin.inc',
  ];

  $items['node/%node/ithenticate'] = [
    'title' => t('iThenticate'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ithenticate_portal', 1],
    'access callback' => 'ithenticate_portal_access',
    'access arguments' => [1],
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function ithenticate_permission() {
  return [
    'administer ithenticate settings' => [
      'title' => 'Administer iThenticate settings',
    ],
    'access ithenticate portal' => [
      'title' => 'Access the ithenticate page for each allowed node',
    ],
    'delete ithenticate document' => [
      'title' => 'Delete iThenticate documents',
    ],
  ];
}

/**
 * Access callback for the iThenticate portal page.
 *
 * @param object $node
 *   The node object.
 *
 * @return bool
 *   Whether the user has access.
 */
function ithenticate_portal_access($node) {
  return $node->type === 'paper' && user_access('access ithenticate portal');
}

/**
 * Callback for the iThenticate portal page.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function ithenticate_portal($form, &$form_state, $node) {
  _validate_ithenticate_is_configured();

  $form_state['#node'] = $node;
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid, $node->revision_id);

  if ($document && $document->getIthenticateReportUrl()) {
    $similarity = $document->getPercentMatch();
    $form['help'] = [
      '#type' => 'item',
      '#markup' => t("The report has been created with <strong>:similarity%</strong> similarity. Please, go to <a href='!link' target='_blank'>iThenticate report page</a> for further details.", [
        '!link' => $document->getIthenticateReportUrl(),
        ':similarity' => $similarity,
      ]),
    ];
  }
  else {
    $form['help'] = [
      '#type' => 'item',
      '#markup' => t('There are no records for the given document. Press below to submit for plagiarism check.'),
    ];
  }

  $query_title = str_replace(' ', '+', $node->title);
  $delete_url = "https://app.ithenticate.com/en_us/search?q={$query_title}";
  $form['delete_url_help'] = [
    '#type' => 'item',
    '#markup' => t('If there is a record in iThenticate, <a target="_blank" href="@url">click here to search</a>.', [
      '@url' => $delete_url,
    ]),
  ];

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Submit to iThenticate'),
    '#access' => empty($document),
    '#submit' => ['ithenticate_portal_submit_document'],
  ];

  $form['fetch_report'] = [
    '#type' => 'submit',
    '#value' => t('Fetch report'),
    '#access' => !empty($document),
    '#submit' => ['ithenticate_portal_fetch_report'],
  ];

  $form['delete'] = [
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#access' => !empty($document) && user_access('delete ithenticate document'),
    '#submit' => ['ithenticate_portal_delete'],
  ];

  if (!empty($document)) {
    $form_state['document'] = $document;
  }

  return $form;
}

/**
 * Submits the document to the iThenticate service.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form_state array.
 */
function ithenticate_portal_submit_document($form, &$form_state) {
  $node = $form_state['#node'];

  $service_wrapper = new IthenticateRequestWrapper();
  $document = $service_wrapper->submitDocument($node);
  $service_wrapper->getReportData($document);
  $document->save();
}

/**
 * Fetches the ithenticate data from the portal.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function ithenticate_portal_fetch_report($form, &$form_state) {
  $node = $form_state['#node'];
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid, $node->revision_id);
  $service_wrapper = new IthenticateRequestWrapper();
  $service_wrapper->getReportData($document);
  $document->save();
}

/**
 * Deletes the ithenticate document.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function ithenticate_portal_delete($form, &$form_state) {
  $node = $form_state['#node'];
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid, $node->revision_id);
  $document->delete();
  drupal_set_message(t('The document has been deleted locally. Please, go to iThenticate to delete it from there.'));
}

/**
 * Submits the document to the iThenticate service.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form_state array.
 */
function ithenticate_portal_submit_fetch_results_submit($form, &$form_state) {
  $node = $form_state['#node'];
  $document = IthenticateDocument::loadByEntityData('node', $node->type, $node->nid, $node->revision_id);
  $service_wrapper = new IthenticateRequestWrapper();

  $service_wrapper->getReportData($document);
  $document->save();
}

/**
 * Checks whether config settings have been set.
 *
 * @return bool
 *   Whether the iThenticate settings are filled.
 */
function _validate_ithenticate_is_configured() {
  $username = variable_get('ithenticate_user_name', '');
  $password = variable_get('ithenticate_user_pass', '');
  $folder_number = variable_get('ithenticate_submission_folder_number', '');

  if (empty($username) || empty($password) || empty($folder_number)) {
    drupal_set_message(t('Please, first configure the iThenticate settings in the <a href="/admin/config/services/ithenticate">settings page</a>.'), 'error');
    return FALSE;
  }

  return TRUE;
}



/**
 * Implements hook_cron().
 */
function ithenticate_cron() {
  $queue = DrupalQueue::get('ithenticate_report_url');
  if ($queue->numberOfItems()) {
    return;
  }

  $document_ids = db_select('ithenticate_documents', 'i')
    ->fields('i', ['ithenticate_document_id'])
    ->isNotNull('ithenticate_document_id')
    ->isNull('ithenticate_report_url')
    ->execute()
    ->fetchCol();

  foreach ($document_ids as $document_id) {
    $queue->createItem($document_id);
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function ithenticate_cron_queue_info() {
  $queues = [];
  $queues['ithenticate_report_url'] = [
    'worker callback' => 'ithenticate_report_download_data',
    'time' => 30,
  ];

  return $queues;
}

/**
 * Attempts to retrieve the report URL for a document.
 *
 * @param int $document_id
 *   The document ID.
 */
function ithenticate_report_download_data($document_id) {
  $document = IthenticateDocument::loadByIthenticateDocumentId($document_id);
  if (empty($document) || !empty($document->getIthenticateReportUrl())) {
    // It has been updated in the meantime. Nothing to do here.
    return;
  }

  $service_wrapper = new IthenticateRequestWrapper();
  $service_wrapper->getReportData($document);
  $document->save();

  if (!empty($document->getIthenticateReportUrl())) {
    $send_email = variable_get('ithenticate_send_email_on_success', FALSE);
    $recipient = variable_get('ithenticate_email_recipient', NULL);
    if ($send_email && filter_var($recipient, FILTER_VALIDATE_EMAIL)) {
      $node = node_load($document->getEntityId());
      drupal_mail('ithenticate', 'report_created', $recipient, LANGUAGE_NONE, [
        'paper_id' => $node->field_paper_id[LANGUAGE_NONE][0]['value'],
        'report_url' => $document->getIthenticateReportUrl(),
        'percent_match' => $document->getPercentMatch(),
      ]);
    }
  }
}

/**
 * Implements hook_mail().
 */
function ithenticate_mail($key, &$message, $params) {
  if ($key !== 'report_created') {
    return;
  }

  $message['subject'] = t("iThenticate report for !paper_id", [
    '!paper_id' => $params['paper_id'],
  ]);
  $message['body'][] = t("A new iThenticate report has been generated. Similarity: !percent_match%. !report_url", [
    '!report_url' => $params['report_url'],
    '!percent_match' => $params['percent_match'],
  ]);
}
